# Árboles de decision para `German.data`
`

Modifique los metodos para el arbol de decision, para poder utilizarlo para classificación. Y apliquelo en los datos de `titanic.csv`

In [27]:
column_name = ['checking', 'duration_', 'history', 'purpose', 'amount_', 'savings',
               'employment', 'installment_', 'personal', 'guarantors', 'recidence_', 
               'property', 'age_', 'other', 'housing', 'credits_',
               'job', 'liable_', 'telephone', 'foreign', 'is_good']
import pandas as pd
import numpy as np
# from scipy.special import expit
%matplotlib inline
import matplotlib.pyplot as plt
#"/media/ibu/SHARED/repos/Credit/data/german.data"
gdata=pd.read_csv("../data/german.data", sep=" ",header = None)
gdata.columns = column_name;
gdat = pd.get_dummies(gdata, drop_first = True).dropna()
# gdat.head()

,duration_,amount_,installment_,recidence_,age_,credits_,liable_,is_good,checking_A12,checking_A13,...,property_A124,other_A142,other_A143,housing_A152,housing_A153,job_A172,job_A173,job_A174,telephone_A192,foreign_A202
0,6,1169,4,4,67,2,1,1,0,0,...,0,0,1,1,0,0,1,0,1,0
1,48,5951,2,2,22,1,1,2,1,0,...,0,0,1,1,0,0,1,0,0,0
2,12,2096,2,3,49,1,2,1,0,0,...,0,0,1,1,0,1,0,0,0,0
3,42,7882,2,4,45,1,2,1,0,0,...,0,0,1,0,1,0,1,0,0,0
4,24,4870,3,4,53,2,2,2,0,0,...,1,0,1,0,1,0,1,0,0,0

In [3]:
attrs = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Survived']
titanic_data = pd.get_dummies(titanic_data[attrs]).dropna()
titanic_data.head(3)

,Pclass,Age,SibSp,Parch,Fare,Survived,Sex_female,Sex_male
PassengerId,,,,,,,,
1,3,22.0,1,0,7.2500,0,0,1
2,1,38.0,1,0,71.2833,1,1,0
3,3,26.0,0,0,7.9250,1,1,0

## Gini Index
$$ G = \sum_{k=1}^K p_{mk} (1 - p_{mk})$$

In [4]:
# Un árbol esta definido por la siguiente estructura
# {'left': None, 'right': None, 'df': df, 'rss': 0}

def _gini_index(df, y):
    """
    Calculate gini_index R, using the target y.
    """
    categories = df[y].unique()
    gini_index = 0
    max_count = -float('inf')
    yhat = None
    for category in categories:
        category_count = (df[y] == category).sum()
        pmk = category_count / len(df)
        gini_index += pmk * (1 - pmk)
        if max_count < category_count:
            max_count = category_count
            yhat = category
    return gini_index, yhat

_gini_index(titanic_data, 'Survived')

(0.48238903404499056, 0)

In [5]:
def _binary_splitting(df, y, x_j):
    """
    Find the best split using the predictor x_j. 
    """
    cut_values = sorted(set(df[x_j]))
    min_s = None
    min_rss, _ = _gini_index(df, y)
    for i in range(len(cut_values) - 1):
        s = (cut_values[i] + cut_values[i+1]) / 2
    
        left_df = df[df[x_j] < s ]
        right_df = df[df[x_j] >= s]
        left_rss, _ = _gini_index(left_df, y)
        right_rss, _ = _gini_index(right_df , y)
        
        # Weighted sum of impurity
        rss = (left_rss*len(left_df) + right_rss*len(right_df))/len(df)
         
        if rss < min_rss:
            min_s = s
            min_rss = rss

    split = {
        'rss': min_rss,
        's': min_s,
        'x_j': x_j,
        'left_df': df[df[x_j] < min_s ],
        'right_df': df[df[x_j] >= min_s]
    }
    return split

_binary_splitting(titanic_data, 'Survived', 'Age')

{'left_df':              Pclass   Age  SibSp  Parch      Fare  Survived  Sex_female  \
 PassengerId
 8                 3  2.00      3      1   21.0750         0           0
 11                3  4.00      1      1   16.7000         1           1
 17                3  2.00      4      1   29.1250         0           0
 44                2  3.00      1      2   41.5792         1           1
 59                2  5.00      1      2   27.7500         1           1
 64                3  4.00      3      2   27.9000         0           0
 79                2  0.83      0      2   29.0000         1           0
 120               3  2.00      4      2   31.2750         0           1
 165               3  1.00      4      1   39.6875         0           0
 172               3  4.00      4      1   29.1250         0           0
 173               3  1.00      1      1   11.1333         1           1
 184               2  1.00      2      1   39.0000         1           0
 185               3  4.00      0      2   22.0250         1           1
 194               2  3.00      1      1   26.0000         1           0
 206               3  2.00      0      1   10.4625         0           1
 234               3  5.00      4      2   31.3875         1           1
 262               3  3.00      4      2   31.3875         1           0
 298               1  2.00      1      2  151.5500         0           1
 306               1  0.92      1      2  151.5500         1           0
 341               2  2.00      1      1   26.0000         1           0
 349               3  3.00      1      1   15.9000         1           0
 375               3  3.00      3      1   21.0750         0           1
 382               3  1.00      0      2   15.7417         1           1
 387               3  1.00      5      2   46.9000         0           0
 408               2  3.00      1      1   18.7500         1           0
 446               1  4.00      0      2   81.8583         1           0
 449               3  5.00      2      1   19.2583         1           1
 470               3  0.75      2      1   19.2583         1           1
 480               3  2.00      0      1   12.2875         1           1
 531               2  2.00      1      1   26.0000         1           1
 619               2  4.00      2      1   39.0000         1           1
 643               3  2.00      3      2   27.9000         0           1
 645               3  0.75      2      1   19.2583         1           1
 692               3  4.00      0      1   13.4167         1           1
 721               2  6.00      0      1   33.0000         1           1
 751               2  4.00      1      1   23.0000         1           1
 752               3  6.00      0      1   12.4750         1           0
 756               2  0.67      1      1   14.5000         1           0
 778               3  5.00      0      0   12.4750         1           1
 789               3  1.00      1      2   20.5750         1           0
 804               3  0.42      0      1    8.5167         1           0
 814               3  6.00      4      2   31.2750         0           1
 825               3  2.00      4      1   39.6875         0           0
 828               2  1.00      0      2   37.0042         1           0
 832               2  0.83      1      1   18.7500         1           0
 851               3  4.00      4      2   31.2750         0           0
 870               3  4.00      1      1   11.1333         1           0

              Sex_male
 PassengerId
 8                   1
 11                  0
 17                  1
 44                  0
 59                  0
 64                  1
 79                  1
 120                 0
 165                 1
 172                 1
 173                 0
 184                 1
 185                 0
 194                 1
 206                 0
 234                 0
 262                 1
 298                 0
 306                 1
 341                 1
 349                 1
 375                 0
 382                 0
 387                 1
 408                 1
 446                 1
 449                 0
 470                 0
 480                 0
 531                 0
 619                 0
 643                 0
 645                 0
 692                 0
 721                 0
 751                 0
 752                 1
 756                 1
 778                 0
 789                 1
 804                 1
 814                 0
 825                 1
 828                 1
 832                 1
 851                 1
 870                 1  ,
 'right_df':              Pclass   Age  SibSp  Parch      Fare  Survived  Sex_female  \
 PassengerId
 1                 3  22.0      1      0    7.2500         0           0
 2                 1  38.0      1      0   71.2833         1           1
 3                 3  26.0      0      0    7.9250         1           1
 4                 1  35.0      1      0   53.1000         1           1
 5                 3  35.0      0      0    8.0500         0           0
 7                 1  54.0      0      0   51.8625         0           0
 9                 3  27.0      0      2   11.1333         1           1
 10                2  14.0      1      0   30.0708         1           1
 12                1  58.0      0      0   26.5500         1           1
 13                3  20.0      0      0    8.0500         0           0
 14                3  39.0      1      5   31.2750         0           0
 15                3  14.0      0      0    7.8542         0           1
 16                2  55.0      0      0   16.0000         1           1
 19                3  31.0      1      0   18.0000         0           1
 21                2  35.0      0      0   26.0000         0           0
 22                2  34.0      0      0   13.0000         1           0
 23                3  15.0      0      0    8.0292         1           1
 24                1  28.0      0      0   35.5000         1           0
 25                3   8.0      3      1   21.0750         0           1
 26                3  38.0      1      5   31.3875         1           1
 28                1  19.0      3      2  263.0000         0           0
 31                1  40.0      0      0   27.7208         0           0
 34                2  66.0      0      0   10.5000         0           0
 35                1  28.0      1      0   82.1708         0           0
 36                1  42.0      1      0   52.0000         0           0
 38                3  21.0      0      0    8.0500         0           0
 39                3  18.0      2      0   18.0000         0           1
 40                3  14.0      1      0   11.2417         1           1
 41                3  40.0      1      0    9.4750         0           1
 42                2  27.0      1      0   21.0000         0           1
 ...             ...   ...    ...    ...       ...       ...         ...
 856               3  18.0      0      1    9.3500         1           1
 857               1  45.0      1      1  164.8667         1           1
 858               1  51.0      0      0   26.5500         1           0
 859               3  24.0      0      3   19.2583         1           1
 861               3  41.0      2      0   14.1083         0           0
 862               2  21.0      1      0   11.5000         0           0
 863               1  48.0      0      0   25.9292         1           1
 865               2  24.0      0      0   13.0000         0           0
 866               2  42.0      0      0   13.0000         1           1
 867               2  27.0      1      0   13.8583         1           1
 868               1  31.0      0      0   50.4958         0           0
 871               3  26.0      0      0    7.8958         0           0
 872               1  47.0      1      1   52.5542         1           1
 873               1  33.0      0      0    5.0000         0           0
 874               3  47.0      0      0    9.0000         0           0
 875               2  28.0      1      0   24.0000         1           1
 876               3  15.0      0      0    7.2250         1           1
 877               3  20.0      0      0    9.8458         0           0
 878               3  19.0      0      0    7.8958         0           0
 880               1  56.0      0      1   83.1583         1           1
 881               2  25.0      0      1   26.0000         1           1
 882               3  33.0      0      0    7.8958         0           0
 883               3  22.0      0      0   10.5167         0           1
 884               2  28.0      0      0   10.5000         0           0
 885               3  25.0      0      0    7.0500         0           0
 886               3  39.0      0      5   29.1250         0           1
 887               2  27.0      0      0   13.0000         0           0
 888               1  19.0      0      0   30.0000         1           1
 890               1  26.0      0      0   30.0000         1           0
 891               3  32.0      0      0    7.7500         0           0

              Sex_male
 PassengerId
 1                   1
 2                   0
 3                   0
 4                   0
 5                   1
 7                   1
 9                   0
 10                  0
 12                  0
 13                  1
 14                  1
 15                  0
 16                  0
 19                  0
 21                  1
 22                  1
 23                  0
 24                  1
 25                  0
 26                  0
 28                  1
 31                  1
 34                  1
 35                  1
 36                  1
 38                  1
 39                  0
 40                  0
 41                  0
 42                  0
 ...               ...
 856                 0
 857                 0
 858                 1
 859                 0
 861                 1
 862                 1
 863                 0
 865                 1
 866                 0
 867                 0
 868                 1
 871                 1
 872                 0
 873                 1
 874                 1
 875                 0
 876                 0
 877                 1
 878                 1
 880                 0
 881                 0
 882                 1
 883                 0
 884                 1
 885                 1
 886                 0
 887                 1
 888                 0
 890                 1
 891                 1

 [667 rows x 8 columns],
 'rss': 0.47004425554074392,
 's': 6.5,
 'x_j': 'Age'}

In [6]:
def _recursive_binary_splitting(df, y, predictors):
    """
    Select the best variable to reduce the
    residual square sum from predictors.
    """
    assert(len(predictors) > 0) # You should have at least one predictor
    min_split = None
    min_rss = float('inf')
    for x_j in predictors:
        split = _binary_splitting(df, y, x_j)
        if split['rss'] < min_rss:
            min_split = split
            min_rss = split['rss']
     
    return {
        'rss': min_rss,
        's': min_split['s'],
        'x_j': min_split['x_j'],
        'left_df': min_split['left_df'],
        'right_df': min_split['right_df']
    }

_recursive_binary_splitting(titanic_data, 'Survived', \
['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_female', 'Sex_male'])

{'left_df':              Pclass   Age  SibSp  Parch      Fare  Survived  Sex_female  \
 PassengerId
 1                 3  22.0      1      0    7.2500         0           0
 5                 3  35.0      0      0    8.0500         0           0
 7                 1  54.0      0      0   51.8625         0           0
 8                 3   2.0      3      1   21.0750         0           0
 13                3  20.0      0      0    8.0500         0           0
 14                3  39.0      1      5   31.2750         0           0
 17                3   2.0      4      1   29.1250         0           0
 21                2  35.0      0      0   26.0000         0           0
 22                2  34.0      0      0   13.0000         1           0
 24                1  28.0      0      0   35.5000         1           0
 28                1  19.0      3      2  263.0000         0           0
 31                1  40.0      0      0   27.7208         0           0
 34                2  66.0      0      0   10.5000         0           0
 35                1  28.0      1      0   82.1708         0           0
 36                1  42.0      1      0   52.0000         0           0
 38                3  21.0      0      0    8.0500         0           0
 51                3   7.0      4      1   39.6875         0           0
 52                3  21.0      0      0    7.8000         0           0
 55                1  65.0      0      1   61.9792         0           0
 58                3  28.5      0      0    7.2292         0           0
 60                3  11.0      5      2   46.9000         0           0
 61                3  22.0      0      0    7.2292         0           0
 63                1  45.0      1      0   83.4750         0           0
 64                3   4.0      3      2   27.9000         0           0
 68                3  19.0      0      0    8.1583         0           0
 70                3  26.0      2      0    8.6625         0           0
 71                2  32.0      0      0   10.5000         0           0
 73                2  21.0      0      0   73.5000         0           0
 74                3  26.0      1      0   14.4542         0           0
 75                3  32.0      0      0   56.4958         1           0
 ...             ...   ...    ...    ...       ...       ...         ...
 834               3  23.0      0      0    7.8542         0           0
 835               3  18.0      0      0    8.3000         0           0
 837               3  21.0      0      0    8.6625         0           0
 839               3  32.0      0      0   56.4958         1           0
 841               3  20.0      0      0    7.9250         0           0
 842               2  16.0      0      0   10.5000         0           0
 844               3  34.5      0      0    6.4375         0           0
 845               3  17.0      0      0    8.6625         0           0
 846               3  42.0      0      0    7.5500         0           0
 848               3  35.0      0      0    7.8958         0           0
 849               2  28.0      0      1   33.0000         0           0
 851               3   4.0      4      2   31.2750         0           0
 852               3  74.0      0      0    7.7750         0           0
 858               1  51.0      0      0   26.5500         1           0
 861               3  41.0      2      0   14.1083         0           0
 862               2  21.0      1      0   11.5000         0           0
 865               2  24.0      0      0   13.0000         0           0
 868               1  31.0      0      0   50.4958         0           0
 870               3   4.0      1      1   11.1333         1           0
 871               3  26.0      0      0    7.8958         0           0
 873               1  33.0      0      0    5.0000         0           0
 874               3  47.0      0      0    9.0000         0           0
 877               3  20.0      0      0    9.8458         0           0
 878               3  19.0      0      0    7.8958         0           0
 882               3  33.0      0      0    7.8958         0           0
 884               2  28.0      0      0   10.5000         0           0
 885               3  25.0      0      0    7.0500         0           0
 887               2  27.0      0      0   13.0000         0           0
 890               1  26.0      0      0   30.0000         1           0
 891               3  32.0      0      0    7.7500         0           0

              Sex_male
 PassengerId
 1                   1
 5                   1
 7                   1
 8                   1
 13                  1
 14                  1
 17                  1
 21                  1
 22                  1
 24                  1
 28                  1
 31                  1
 34                  1
 35                  1
 36                  1
 38                  1
 51                  1
 52                  1
 55                  1
 58                  1
 60                  1
 61                  1
 63                  1
 64                  1
 68                  1
 70                  1
 71                  1
 73                  1
 74                  1
 75                  1
 ...               ...
 834                 1
 835                 1
 837                 1
 839                 1
 841                 1
 842                 1
 844                 1
 845                 1
 846                 1
 848                 1
 849                 1
 851                 1
 852                 1
 858                 1
 861                 1
 862                 1
 865                 1
 868                 1
 870                 1
 871                 1
 873                 1
 874                 1
 877                 1
 878                 1
 882                 1
 884                 1
 885                 1
 887                 1
 890                 1
 891                 1

 [453 rows x 8 columns],
 'right_df':              Pclass   Age  SibSp  Parch      Fare  Survived  Sex_female  \
 PassengerId
 2                 1  38.0      1      0   71.2833         1           1
 3                 3  26.0      0      0    7.9250         1           1
 4                 1  35.0      1      0   53.1000         1           1
 9                 3  27.0      0      2   11.1333         1           1
 10                2  14.0      1      0   30.0708         1           1
 11                3   4.0      1      1   16.7000         1           1
 12                1  58.0      0      0   26.5500         1           1
 15                3  14.0      0      0    7.8542         0           1
 16                2  55.0      0      0   16.0000         1           1
 19                3  31.0      1      0   18.0000         0           1
 23                3  15.0      0      0    8.0292         1           1
 25                3   8.0      3      1   21.0750         0           1
 26                3  38.0      1      5   31.3875         1           1
 39                3  18.0      2      0   18.0000         0           1
 40                3  14.0      1      0   11.2417         1           1
 41                3  40.0      1      0    9.4750         0           1
 42                2  27.0      1      0   21.0000         0           1
 44                2   3.0      1      2   41.5792         1           1
 45                3  19.0      0      0    7.8792         1           1
 50                3  18.0      1      0   17.8000         0           1
 53                1  49.0      1      0   76.7292         1           1
 54                2  29.0      1      0   26.0000         1           1
 57                2  21.0      0      0   10.5000         1           1
 59                2   5.0      1      2   27.7500         1           1
 62                1  38.0      0      0   80.0000         1           1
 67                2  29.0      0      0   10.5000         1           1
 69                3  17.0      4      2    7.9250         1           1
 72                3  16.0      5      2   46.9000         0           1
 80                3  30.0      0      0   12.4750         1           1
 85                2  17.0      0      0   10.5000         1           1
 ...             ...   ...    ...    ...       ...       ...         ...
 798               3  31.0      0      0    8.6833         1           1
 800               3  30.0      1      1   24.1500         0           1
 802               2  31.0      1      1   26.2500         1           1
 808               3  18.0      0      0    7.7750         0           1
 810               1  33.0      1      0   53.1000         1           1
 814               3   6.0      4      2   31.2750         0           1
 817               3  23.0      0      0    7.9250         0           1
 821               1  52.0      1      1   93.5000         1           1
 824               3  27.0      0      1   12.4750         1           1
 830               1  62.0      0      0   80.0000         1           1
 831               3  15.0      1      0   14.4542         1           1
 836               1  39.0      1      1   83.1583         1           1
 843               1  30.0      0      0   31.0000         1           1
 853               3   9.0      1      1   15.2458         0           1
 854               1  16.0      0      1   39.4000         1           1
 855               2  44.0      1      0   26.0000         0           1
 856               3  18.0      0      1    9.3500         1           1
 857               1  45.0      1      1  164.8667         1           1
 859               3  24.0      0      3   19.2583         1           1
 863               1  48.0      0      0   25.9292         1           1
 866               2  42.0      0      0   13.0000         1           1
 867               2  27.0      1      0   13.8583         1           1
 872               1  47.0      1      1   52.5542         1           1
 875               2  28.0      1      0   24.0000         1           1
 876               3  15.0      0      0    7.2250         1           1
 880               1  56.0      0      1   83.1583         1           1
 881               2  25.0      0      1   26.0000         1           1
 883               3  22.0      0      0   10.5167         0           1
 886               3  39.0      0      5   29.1250         0           1
 888               1  19.0      0      0   30.0000         1           1

              Sex_male
 PassengerId
 2                   0
 3                   0
 4                   0
 9                   0
 10                  0
 11                  0
 12                  0
 15                  0
 16                  0
 19                  0
 23                  0
 25                  0
 26                  0
 39                  0
 40                  0
 41                  0
 42                  0
 44                  0
 45                  0
 50                  0
 53                  0
 54                  0
 57                  0
 59                  0
 62                  0
 67                  0
 69                  0
 72                  0
 80                  0
 85                  0
 ...               ...
 798                 0
 800                 0
 802                 0
 808                 0
 810                 0
 814                 0
 817                 0
 821                 0
 824                 0
 830                 0
 831                 0
 836                 0
 843                 0
 853                 0
 854                 0
 855                 0
 856                 0
 857                 0
 859                 0
 863                 0
 866                 0
 867                 0
 872                 0
 875                 0
 876                 0
 880                 0
 881                 0
 883                 0
 886                 0
 888                 0

 [261 rows x 8 columns],
 'rss': 0.34233556912653673,
 's': 0.5,
 'x_j': 'Sex_female'}

In [7]:
def _make_tree(df, y):
    rss, yhat = _gini_index(df, y)
    return {'left': None, 'right':None, 
            'rss': rss,
            'yhat': yhat,
            'df': df,
            'y': y}

def _grow_tree(tree, predictors, min_points_per_leaf=5):
    """
    Recursively divide tree using the split that
    minimize rss. It stops when the region have
    less than 5 elements.
    """
    if len(tree['df']) <= min_points_per_leaf:
        return tree
    
    split = _recursive_binary_splitting(tree['df'], tree['y'], predictors)
    if split['s'] is None:
        return tree
    left_tree = _make_tree(split['left_df'], tree['y'])
    right_tree = _make_tree(split['right_df'],  tree['y'])

    _grow_tree(left_tree, predictors, min_points_per_leaf=min_points_per_leaf)
    _grow_tree(right_tree, predictors, min_points_per_leaf=min_points_per_leaf)
    
    tree['left'] = left_tree
    tree['right'] = right_tree
    tree['x_j'] = split['x_j']
    tree['s'] = split['s']
    
    return tree

titanic_tree = _make_tree(titanic_data, 'Survived')
_grow_tree(titanic_tree, \
  ['Age', 'SibSp', 'Parch', 'Fare', 'Sex_female', 'Sex_male'],
  min_points_per_leaf=1);

In [8]:
titanic_tree

{'df':              Pclass   Age  SibSp  Parch      Fare  Survived  Sex_female  \
 PassengerId
 1                 3  22.0      1      0    7.2500         0           0
 2                 1  38.0      1      0   71.2833         1           1
 3                 3  26.0      0      0    7.9250         1           1
 4                 1  35.0      1      0   53.1000         1           1
 5                 3  35.0      0      0    8.0500         0           0
 7                 1  54.0      0      0   51.8625         0           0
 8                 3   2.0      3      1   21.0750         0           0
 9                 3  27.0      0      2   11.1333         1           1
 10                2  14.0      1      0   30.0708         1           1
 11                3   4.0      1      1   16.7000         1           1
 12                1  58.0      0      0   26.5500         1           1
 13                3  20.0      0      0    8.0500         0           0
 14                3  39.0      1      5   31.2750         0           0
 15                3  14.0      0      0    7.8542         0           1
 16                2  55.0      0      0   16.0000         1           1
 17                3   2.0      4      1   29.1250         0           0
 19                3  31.0      1      0   18.0000         0           1
 21                2  35.0      0      0   26.0000         0           0
 22                2  34.0      0      0   13.0000         1           0
 23                3  15.0      0      0    8.0292         1           1
 24                1  28.0      0      0   35.5000         1           0
 25                3   8.0      3      1   21.0750         0           1
 26                3  38.0      1      5   31.3875         1           1
 28                1  19.0      3      2  263.0000         0           0
 31                1  40.0      0      0   27.7208         0           0
 34                2  66.0      0      0   10.5000         0           0
 35                1  28.0      1      0   82.1708         0           0
 36                1  42.0      1      0   52.0000         0           0
 38                3  21.0      0      0    8.0500         0           0
 39                3  18.0      2      0   18.0000         0           1
 ...             ...   ...    ...    ...       ...       ...         ...
 857               1  45.0      1      1  164.8667         1           1
 858               1  51.0      0      0   26.5500         1           0
 859               3  24.0      0      3   19.2583         1           1
 861               3  41.0      2      0   14.1083         0           0
 862               2  21.0      1      0   11.5000         0           0
 863               1  48.0      0      0   25.9292         1           1
 865               2  24.0      0      0   13.0000         0           0
 866               2  42.0      0      0   13.0000         1           1
 867               2  27.0      1      0   13.8583         1           1
 868               1  31.0      0      0   50.4958         0           0
 870               3   4.0      1      1   11.1333         1           0
 871               3  26.0      0      0    7.8958         0           0
 872               1  47.0      1      1   52.5542         1           1
 873               1  33.0      0      0    5.0000         0           0
 874               3  47.0      0      0    9.0000         0           0
 875               2  28.0      1      0   24.0000         1           1
 876               3  15.0      0      0    7.2250         1           1
 877               3  20.0      0      0    9.8458         0           0
 878               3  19.0      0      0    7.8958         0           0
 880               1  56.0      0      1   83.1583         1           1
 881               2  25.0      0      1   26.0000         1           1
 882               3  33.0      0      0    7.8958         0           0
 883               3  22.0      0      0   10.5167         0           1
 884               2  28.0      0      0   10.5000         0           0
 885               3  25.0      0      0    7.0500         0           0
 886               3  39.0      0      5   29.1250         0           1
 887               2  27.0      0      0   13.0000         0           0
 888               1  19.0      0      0   30.0000         1           1
 890               1  26.0      0      0   30.0000         1           0
 891               3  32.0      0      0    7.7500         0           0

              Sex_male
 PassengerId
 1                   1
 2                   0
 3                   0
 4                   0
 5                   1
 7                   1
 8                   1
 9                   0
 10                  0
 11                  0
 12                  0
 13                  1
 14                  1
 15                  0
 16                  0
 17                  1
 19                  0
 21                  1
 22                  1
 23                  0
 24                  1
 25                  0
 26                  0
 28                  1
 31                  1
 34                  1
 35                  1
 36                  1
 38                  1
 39                  0
 ...               ...
 857                 0
 858                 1
 859                 0
 861                 1
 862                 1
 863                 0
 865                 1
 866                 0
 867                 0
 868                 1
 870                 1
 871                 1
 872                 0
 873                 1
 874                 1
 875                 0
 876                 0
 877                 1
 878                 1
 880                 0
 881                 0
 882                 1
 883                 0
 884                 1
 885                 1
 886                 0
 887                 1
 888                 0
 890                 1
 891                 1

 [714 rows x 8 columns],
 'left': {'df':              Pclass   Age  SibSp  Parch      Fare  Survived  Sex_female  \
  PassengerId
  1                 3  22.0      1      0    7.2500         0           0
  5                 3  35.0      0      0    8.0500         0           0
  7                 1  54.0      0      0   51.8625         0           0
  8                 3   2.0      3      1   21.0750         0           0
  13                3  20.0      0      0    8.0500         0           0
  14                3  39.0      1      5   31.2750         0           0
  17                3   2.0      4      1   29.1250         0           0
  21                2  35.0      0      0   26.0000         0           0
  22                2  34.0      0      0   13.0000         1           0
  24                1  28.0      0      0   35.5000         1           0
  28                1  19.0      3      2  263.0000         0           0
  31                1  40.0      0      0   27.7208         0           0
  34                2  66.0      0      0   10.5000         0           0
  35                1  28.0      1      0   82.1708         0           0
  36                1  42.0      1      0   52.0000         0           0
  38                3  21.0      0      0    8.0500         0           0
  51                3   7.0      4      1   39.6875         0           0
  52                3  21.0      0      0    7.8000         0           0
  55                1  65.0      0      1   61.9792         0           0
  58                3  28.5      0      0    7.2292         0           0
  60                3  11.0      5      2   46.9000         0           0
  61                3  22.0      0      0    7.2292         0           0
  63                1  45.0      1      0   83.4750         0           0
  64                3   4.0      3      2   27.9000         0           0
  68                3  19.0      0      0    8.1583         0           0
  70                3  26.0      2      0    8.6625         0           0
  71                2  32.0      0      0   10.5000         0           0
  73                2  21.0      0      0   73.5000         0           0
  74                3  26.0      1      0   14.4542         0           0
  75                3  32.0      0      0   56.4958         1           0
  ...             ...   ...    ...    ...       ...       ...         ...
  834               3  23.0      0      0    7.8542         0           0
  835               3  18.0      0      0    8.3000         0           0
  837               3  21.0      0      0    8.6625         0           0
  839               3  32.0      0      0   56.4958         1           0
  841               3  20.0      0      0    7.9250         0           0
  842               2  16.0      0      0   10.5000         0           0
  844               3  34.5      0      0    6.4375         0           0
  845               3  17.0      0      0    8.6625         0           0
  846               3  42.0      0      0    7.5500         0           0
  848               3  35.0      0      0    7.8958         0           0
  849               2  28.0      0      1   33.0000         0           0
  851               3   4.0      4      2   31.2750         0           0
  852               3  74.0      0      0    7.7750         0           0
  858               1  51.0      0      0   26.5500         1           0
  861               3  41.0      2      0   14.1083         0           0
  862               2  21.0      1      0   11.5000         0           0
  865               2  24.0      0      0   13.0000         0           0
  868               1  31.0      0      0   50.4958         0           0
  870               3   4.0      1      1   11.1333         1           0
  871               3  26.0      0      0    7.8958         0           0
  873               1  33.0      0      0    5.0000         0           0
  874               3  47.0      0      0    9.0000         0           0
  877               3  20.0      0      0    9.8458         0           0
  878               3  19.0      0      0    7.8958         0           0
  882               3  33.0      0      0    7.8958         0           0
  884               2  28.0      0      0   10.5000         0           0
  885               3  25.0      0      0    7.0500         0           0
  887               2  27.0      0      0   13.0000         0           0
  890               1  26.0      0      0   30.0000         1           0
  891               3  32.0      0      0    7.7500         0           0

               Sex_male
  PassengerId
  1                   1
  5                   1
  7                   1
  8                   1
  13                  1
  14                  1
  17                  1
  21                  1
  22                  1
  24                  1
  28                  1
  31                  1
  34                  1
  35                  1
  36                  1
  38                  1
  51                  1
  52                  1
  55                  1
  58                  1
  60                  1
  61                  1
  63                  1
  64                  1
  68                  1
  70                  1
  71                  1
  73                  1
  74                  1
  75                  1
  ...               ...
  834                 1
  835                 1
  837                 1
  839                 1
  841                 1
  842                 1
  844                 1
  845                 1
  846                 1
  848                 1
  849                 1
  851                 1
  852                 1
  858                 1
  861                 1
  862                 1
  865                 1
  868                 1
  870                 1
  871                 1
  873                 1
  874                 1
  877                 1
  878                 1
  882                 1
  884                 1
  885                 1
  887                 1
  890                 1
  891                 1

  [453 rows x 8 columns],
  'left': {'df':              Pclass   Age  SibSp  Parch      Fare  Survived  Sex_female  \
   PassengerId
   8                 3  2.00      3      1   21.0750         0           0
   17                3  2.00      4      1   29.1250         0           0
   64                3  4.00      3      2   27.9000         0           0
   79                2  0.83      0      2   29.0000         1           0
   165               3  1.00      4      1   39.6875         0           0
   172               3  4.00      4      1   29.1250         0           0
   184               2  1.00      2      1   39.0000         1           0
   194               2  3.00      1      1   26.0000         1           0
   262               3  3.00      4      2   31.3875         1           0
   306               1  0.92      1      2  151.5500         1           0
   341               2  2.00      1      1   26.0000         1           0
   349               3  3.00      1      1   15.9000         1           0
   387               3  1.00      5      2   46.9000         0           0
   408               2  3.00      1      1   18.7500         1           0
   446               1  4.00      0      2   81.8583         1           0
   752               3  6.00      0      1   12.4750         1           0
   756               2  0.67      1      1   14.5000         1           0
   789               3  1.00      1      2   20.5750         1           0
   804               3  0.42      0      1    8.5167         1           0
   825               3  2.00      4      1   39.6875         0           0
   828               2  1.00      0      2   37.0042         1           0
   832               2  0.83      1      1   18.7500         1           0
   851               3  4.00      4      2   31.2750         0           0
   870               3  4.00      1      1   11.1333         1           0

                Sex_male
   PassengerId
   8                   1
   17                  1
   64                  1
   79                  1
   165                 1
   172                 1
   184                 1
   194                 1
   262                 1
   306                 1
   341                 1
   349                 1
   387                 1
   408                 1
   446                 1
   752                 1
   756                 1
   789                 1
   804                 1
   825                 1
   828                 1
   832                 1
   851                 1
   870                 1  ,
   'left': {'df':              Pclass   Age  SibSp  Parch      Fare  Survived  Sex_female  \
    PassengerId
    79                2  0.83      0      2   29.0000         1           0
    184               2  1.00      2      1   39.0000         1           0
    194               2  3.00      1      1   26.0000         1           0
    306               1  0.92      1      2  151.5500         1           0
    341               2  2.00      1      1   26.0000         1           0
    349               3  3.00      1      1   15.9000         1           0
    408               2  3.00      1      1   18.7500         1           0
    446               1  4.00      0      2   81.8583         1           0
    752               3  6.00      0      1   12.4750         1           0
    756               2  0.67      1      1   14.5000         1           0
    789               3  1.00      1      2   20.5750         1           0
    804               3  0.42      0      1    8.5167         1           0
    828               2  1.00      0      2   37.0042         1           0
    832               2  0.83      1      1   18.7500         1           0
    870               3  4.00      1      1   11.1333         1           0

                 Sex_male
    PassengerId
    79                  1
    184                 1
    194                 1
    306                 1
    341                 1
    349                 1
    408                 1
    446                 1
    752                 1
    756                 1
    789                 1
    804                 1
    828                 1
    832                 1
    870                 1  ,
    'left': None,
    'right': None,
    'rss': 0.0,
    'y': 'Survived',
    'yhat': 1},
   'right': {'df':              Pclass  Age  SibSp  Parch     Fare  Survived  Sex_female  \
    PassengerId
    8                 3  2.0      3      1  21.0750         0           0
    17                3  2.0      4      1  29.1250         0           0
    64                3  4.0      3      2  27.9000         0           0
    165               3  1.0      4      1  39.6875         0           0
    172               3  4.0      4      1  29.1250         0           0
    262               3  3.0      4      2  31.3875         1           0
    387               3  1.0      5      2  46.9000         0           0
    825               3  2.0      4      1  39.6875         0           0
    851               3  4.0      4      2  31.2750         0           0

                 Sex_male
    PassengerId
    8                   1
    17                  1
    64                  1
    165                 1
    172                 1
    262                 1
    387                 1
    825                 1
    851                 1  ,
    'left': {'df':              Pclass  Age  SibSp  Parch     Fare  Survived  Sex_female  \
     PassengerId
     8                 3  2.0      3      1  21.0750         0           0
     17                3  2.0      4      1  29.1250         0           0
     165               3  1.0      4      1  39.6875         0           0
     387               3  1.0      5      2  46.9000         0           0
     825               3  2.0      4      1  39.6875         0           0

                  Sex_male
     PassengerId
     8                   1
     17                  1
     165                 1
     387                 1
     825                 1  ,
     'left': None,
     'right': None,
     'rss': 0.0,
     'y': 'Survived',
     'yhat': 0},
    'right': {'df':              Pclass  Age  SibSp  Parch     Fare  Survived  Sex_female  \
     PassengerId
     64                3  4.0      3      2  27.9000         0           0
     172               3  4.0      4      1  29.1250         0           0
     262               3  3.0      4      2  31.3875         1           0
     851               3  4.0      4      2  31.2750         0           0

                  Sex_male
     PassengerId
     64                  1
     172                 1
     262                 1
     851                 1  ,
     'left': {'df':              Pclass  Age  SibSp  Parch     Fare  Survived  Sex_female  \
      PassengerId
      262               3  3.0      4      2  31.3875         1           0

                   Sex_male
      PassengerId
      262                 1  ,
      'left': None,
      'right': None,
      'rss': 0.0,
      'y': 'Survived',
      'yhat': 1},
     'right': {'df':              Pclass  Age  SibSp  Parch    Fare  Survived  Sex_female  Sex_male
      PassengerId
      64                3  4.0      3      2  27.900         0           0         1
      172               3  4.0      4      1  29.125         0           0         1
      851               3  4.0      4      2  31.275         0           0         1,
      'left': None,
      'right': None,
      'rss': 0.0,
      'y': 'Survived',
      'yhat': 0},
     'rss': 0.375,
     's': 3.5,
     'x_j': 'Age',
     'y': 'Survived',
     'yhat': 0},
    'rss': 0.19753086419753091,
    's': 2.5,
    'x_j': 'Age',
    'y': 'Survived',
    'yhat': 0},
   'rss': 0.44444444444444448,
   's': 2.5,
   'x_j': 'SibSp',
   'y': 'Survived',

In [9]:
def print_tree(tree, pad=0):
    print('{}rss'.format(' '*pad), tree['rss'], tree['yhat'])
    if tree['left']:
        print_tree(tree['left'], pad=pad+1)
    if tree['right']:
        print_tree(tree['right'], pad=pad+1)

In [10]:
#print_tree(titanic_tree)

In [11]:
def _is_leaf(tree):
    """
    Return if a given tree is a leaf.
    """
    return not tree['left'] and not tree['right']

def _tree_rss(tree):
    """
    Calculate the total rss of a tree: the sum of the rss of
    all leaves.
    """
    if _is_leaf(tree):
        return tree['rss']

    wsum = len(tree['left']['df']) * _tree_rss(tree['left']) \
             + len(tree['right']['df']) * _tree_rss(tree['right'])
    return wsum/len(tree['df'])

_tree_rss(titanic_tree)

0.014939309056956118

In [12]:
def _count_leafs(tree):
    """
    Return the number of leaves in the tree.
    """
    if _is_leaf(tree):
        return 1
    
    return _count_leafs(tree['left']) + _count_leafs(tree['right'])

_count_leafs(titanic_tree)

177

In [13]:
def _is_last_branch(tree):
    """
    Return if a given tree is the last branch, i.e. both 
    subtrees are leaves.
    """
    return _is_leaf(tree['left']) and _is_leaf(tree['right'])

def _find_min_deltarss(tree):
    """
    Find the tree that reduces for which the split reduces
    the least the rss.
    """
    if _is_last_branch(tree):
        return tree['rss'] - _tree_rss(tree), tree
    
    is_left_leaf = _is_leaf(tree['left'])
    is_right_leaf = _is_leaf(tree['right'])
    
    if is_left_leaf and not is_right_leaf:
        return _find_min_deltarss(tree['right'])
    elif not is_left_leaf and is_right_leaf:
        return _find_min_deltarss(tree['left'])
    
    deltarss_left, left_tree_branch = _find_min_deltarss(tree['left'])
    deltarss_right, right_tree_branch = _find_min_deltarss(tree['right'])
    
    if deltarss_left < deltarss_right:
        return deltarss_left, left_tree_branch
    else:
        return deltarss_right, right_tree_branch
    
    return min_deltarss, min_tree

_find_min_deltarss(titanic_tree)

(0.04166666666666663,
 {'df':              Pclass   Age  SibSp  Parch    Fare  Survived  Sex_female  \
  PassengerId
  383               3  32.0      0      0  7.9250         0           0
  520               3  32.0      0      0  7.8958         0           0
  580               3  32.0      0      0  7.9250         1           0
  637               3  32.0      0      0  7.9250         0           0

               Sex_male
  PassengerId
  383                 1
  520                 1
  580                 1
  637                 1  ,
  'left': {'df':              Pclass   Age  SibSp  Parch    Fare  Survived  Sex_female  \
   PassengerId
   520               3  32.0      0      0  7.8958         0           0

                Sex_male
   PassengerId
   520                 1  ,
   'left': None,
   'right': None,
   'rss': 0.0,
   'y': 'Survived',
   'yhat': 0},
  'right': {'df':              Pclass   Age  SibSp  Parch   Fare  Survived  Sex_female  Sex_male
   PassengerId
   383               3  32.0      0      0  7.925         0           0         1
   580               3  32.0      0      0  7.925         1           0         1
   637               3  32.0      0      0  7.925         0           0         1,
   'left': None,
   'right': None,
   'rss': 0.44444444444444448,
   'y': 'Survived',
   'yhat': 0},
  'rss': 0.375,
  's': 7.9104000000000001,
  'x_j': 'Fare',
  'y': 'Survived',
  'yhat': 0})

In [14]:
from copy import deepcopy

def _prune_tree(tree, alpha):
    current_tree = deepcopy(tree)
    min_cc_tree = deepcopy(current_tree)
    min_cc = _tree_rss(current_tree) + alpha * _count_leafs(current_tree)
    while not _is_leaf(current_tree):
        delta_rss, prune_tree = _find_min_deltarss(current_tree)
        prune_tree['left'] = None
        prune_tree['right'] = None
        cc = _tree_rss(current_tree) + alpha * _count_leafs(current_tree)
        #print(cc, min_cc, cc < min_cc)
        if cc < min_cc:
            min_cc = cc
            min_cc_tree = deepcopy(current_tree)
    cc = _tree_rss(current_tree) + alpha * _count_leafs(current_tree)
    if cc < min_cc:
        min_cc = cc
        min_cc_tree = deepcopy(current_tree)   
        
    return min_cc_tree

pruned_tree = _prune_tree(titanic_tree, 0.005)
_tree_rss(pruned_tree)

0.3151211245942217

# Visualización

In [15]:
import graphviz
from IPython import display

def make_node(g, name, tree):
    attributes = {'label': 'rss: {:0.4f}'.format(tree['rss']),
                  'shape': 'square'}
    if tree.get('yhat'):
        attributes['label'] += '\n yhat: {:0.2f}'.format(tree['yhat'])
    g.node(name, **attributes)
    
def make_edge(g, parent, child, tree, direction):
    attributes = {}
    if direction == 'l':
        attributes['label'] = '{} < {}'.format(tree['x_j'], tree['s'])
    if direction == 'r':
        attributes['label'] = '{} >= {}'.format(tree['x_j'], tree['s'])
    g.edge(parent, child, **attributes)
    

def construct_tree(g, dna, tree):
    if not tree['left'] and not tree['right']:
        make_node(g, dna, tree)
    else:
        make_node(g, dna + 'l', tree['left'])
        make_edge(g, dna, dna + 'l', tree, 'l')
        construct_tree(g, dna + 'l', tree['left'])

        make_node(g, dna + 'r', tree['right'])
        make_edge(g, dna, dna + 'r', tree, 'r')
        construct_tree(g, dna + 'r', tree['right'])
        
def visualize_tree(tree):
    g = graphviz.Graph('tree', 'tree.dot', engine='dot')
    make_node(g, 'r', tree)
    construct_tree(g, 'r', tree)
    display.display(g)

In [16]:
#visualize_tree(titanic_tree)

In [17]:
visualize_tree(pruned_tree)

# Evaluación del árbol

In [18]:
def _evaluate(tree, event):
    if tree['left'] == None and tree['right'] == None:
        return tree['yhat']
    if event[tree['x_j']] < tree['s']:
        return _evaluate(tree['left'], event)
    else:
        return _evaluate(tree['right'], event)

_evaluate(pruned_tree, titanic_data.iloc[0])

0

In [19]:
titanic_data['yhat'] = titanic_data.apply(lambda row: _evaluate(pruned_tree, row), axis=1)

In [20]:
titanic_data.head()

,Pclass,Age,SibSp,Parch,Fare,Survived,Sex_female,Sex_male,yhat
PassengerId,,,,,,,,,
1,3,22.0,1,0,7.2500,0,0,1,0
2,1,38.0,1,0,71.2833,1,1,0,1
3,3,26.0,0,0,7.9250,1,1,0,1
4,1,35.0,1,0,53.1000,1,1,0,1
5,3,35.0,0,0,8.0500,0,0,1,0

# Matriz de confución

In [21]:
(titanic_data[titanic_data.Survived == 1].yhat == 1).sum()

213

In [22]:
(titanic_data[titanic_data.Survived == 1].yhat == 0).sum()

77

In [23]:
(titanic_data[titanic_data.Survived == 0].yhat == 1).sum()

72

In [24]:
(titanic_data[titanic_data.Survived == 0].yhat == 0).sum()

352