Intente aplicar el algoritmo del perceptrón a los datos de prestamos Alemánes.
Transforme las columnas de datos categoricos en una columna para cada categoría. Por ejémplo, `genero` => `genero_hombre`, `genero_mujer` donde `genero_hombre` es `1` si es hombre y `0` de lo contrario. Puede utilizar la funcion `get_dummies` de pandas (`pd.get_dummies(dataset)`)

In [12]:
attribute_desc = {
# Status of existing checking account
'A11': "... <    0 DM",
'A12': '0 <= ... <  200 DM',
'A13': '     ... >= 200 DM',
'A14': 'no checking account',
# Duration in month
# Credit history
'A30': 'no credits taken',
'A31': 'all credits at this bank paid back duly',
'A32': 'existing credits paid back duly till now',
'A33': 'delay in paying off in the past',
'A34': 'critical account',
# Purpose
'A40': 'car (new)',
'A41': 'car (used)',
'A42': 'furniture/equipment',
'A43': 'radio/television',
'A44': 'domestic appliances',
'A45': 'repairs',
'A46': 'education',
'A47': 'vacation',
'A48': 'retraining',
'A49': 'business',
'A410': 'others',
# Credit amount
# Savings account/bonds
'A61':   '       ... <  100 DM',
'A62':   '100 <= ... <  500 DM',
'A63':   '500 <= ... < 1000 DM',
'A64':   '       .. >= 1000 DM',
'A65':   'unknown/ no savings account',
#Present employment since
'A71' : 'unemployed',
'A72' :  '... < 1 year',
'A73' : '1  <= ... < 4 years',
'A74' : '4  <= ... < 7 years',
'A75' : '.. >= 7 years',
# Installment rate in percentage of disposable income
# Personal status and sex
'A91' : 'male   : divorced/separated',
'A92' : 'female : divorced/separated/married',
'A93' : 'male   : single',
'A94' : 'male   : married/widowed',
'A95' : 'female : single',
#Other debtors / guarantors
'A101' : 'none',
'A102' : 'co-applicant',
'A103' : 'guarantor',
#Present residence since
#Property
'A121' : 'real estate',
'A122' : 'if not A121 : building society savings agreement/life insurance',
'A123' : 'if not A121/A122 : car or other, not in attribute 6',
'A124' : 'unknown / no property',
# Age in years
# Other installment plans 
'A141' : 'bank',
'A142' : 'stores',
'A143' : 'none',
# Housing
'A151' : 'rent',
'A152' : 'own',
'A153' : 'for free',
# Number of existing credits at this bank
# Job
'A171': 'unemployed/ unskilled - non-resident',
'A172': 'unskilled - resident',
'A173': 'skilled employee / official',
'A174': 'management/self-employed/highly qualified employee/officer',
# Number of people being liable to provide maintenance for
# Telephone
'A191': 'none',
'A192': 'yes, registered under the customers name',
# Foreign worker
'A201': 'yes',
'A202': 'no',
}

column_name = ['checking', 'duration_', 'history', 'purpose', 'amount_', 'savings',
               'employment', 'installment_', 'personal', 'guarantors', 'recidence_', 
               'property', 'age_', 'other', 'housing', 'credits_',
               'job', 'liable_', 'telephone', 'foreign', 'is_good']

In [120]:
import pandas as pd
import os
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
gdata=pd.read_csv("/media/ibu/SHARED/repos/Credit/data/german.data", sep=" ",header = None)
gdata.columns = column_name;
#os.getcwd()

gdata=pd.get_dummies(gdata);

W = np.random.randn(3);
gdata.loc[:,gdata.columns.map(lambda x: x.startswith('hist')).values]

     history_A30  history_A31  history_A32  history_A33  history_A34
0              0            0            0            0            1
1              0            0            1            0            0
2              0            0            0            0            1
3              0            0            1            0            0
4              0            0            0            1            0
5              0            0            1            0            0
6              0            0            1            0            0
7              0            0            1            0            0
8              0            0            1            0            0
9              0            0            0            0            1
10             0            0            1            0            0
11             0            0            1            0            0
12             0            0            1            0            0
13             0            0            0            0            1
14             0            0            1            0            0
15             0            0            1            0            0
16             0            0            0            0            1
17             1            0            0            0            0
18             0            0            1            0            0
19             0            0            1            0            0
20             0            0            0            0            1
21             0            0            1            0            0
22             0            0            0            0            1
23             0            0            0            0            1
24             0            0            0            0            1
25             0            0            1            0            0
26             1            0            0            0            0
27             0            1            0            0            0
28             0            0            1            0            0
29             0            0            0            1            0
..           ...          ...          ...          ...          ...
870            0            0            0            1            0
871            0            0            0            0            1
872            0            0            0            0            1
873            0            0            1            0            0
874            0            0            1            0            0
875            0            0            0            0            1
876            0            1            0            0            0
877            0            0            1            0            0
878            0            0            1            0            0
879            0            0            0            0            1
880            0            0            1            0            0
881            0            0            1            0            0
882            0            0            0            0            1
883            0            0            0            0            1
884            0            0            1            0            0
885            0            0            1            0            0
886            0            0            0            0            1
887            0            0            1            0            0
888            0            0            0            0            1
889            0            1            0            0            0
890            0            0            0            0            1
891            0            0            0            0            1
892            0            0            0            0            1
893            0            0            0            0            1
894            0            0            0            0            1
895            0            0            0            1            0
896            0            0            1            0            0
897            0            0            0            0            1
898            0            0            1            0            0
899            0            0            1            0            0

[900 rows x 5 columns]

¿Funcionó? ¿Qué ocurrio?

Grafique el error en la muestra para cada paso del entrenamiento durante los primeros 1000 pasos.